# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               David McDonald's Blog
tagline:             'About tech, cooking, photography and stuff'
description:         'David is Microsoft Technologist who enjoys geeking out as well as cooking, photography and other geeky pursuits.'
url:                 http://localhost:4000
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              David McDonald
  url:               https://twitter.com/davidmcd
  email:             davidmcdmsft@hotmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
